### ISSUE TITLE
Implement Ratings History Graph & Ratings Distribution Graph in Profile App

### ISSUE THREAD

**Issue by rakibansary** [topcoder-platform/micro-frontends-profile-app#6]
Challenge Link: https://www.topcoder.com/challenges/c7ed757b-a945-4046-8aac-6dca49f4d8e1

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2021-10-14 at 12 08 51 PM" src="https://user-images.githubusercontent.com/58783823/137264818-e0f8cc81-e7e5-42f3-8824-4af4a7d443ce.png">
<img width="1440" alt="Screenshot 2021-10-14 at 12 08 55 PM" src="https://user-images.githubusercontent.com/58783823/137264832-540af2ad-cd65-4643-9f39-d19d110b8f0f.png">
