### ISSUE TITLE
The Challenge links in the History Graph is pointing to wrong url

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-profile-app#8]
Description:
The Challenge links in the History Graph is pointing to wrong URL. 

It should be https://platform.topcoder-dev.com/earn/find/challenges/30009978

![image](https://user-images.githubusercontent.com/55895538/136916728-d8c940d1-e92f-4b3b-b4af-877857724554.png)

**Comment by rakibansary** [comment]
Hi @sandhiyakavi - this is ready for QA. Data Science match details are still opened in Community App. All other challenge details are opened in Earn App. Earn app does not seem to yet support loading details using legacy challenge id and is in progress - https://github.com/topcoder-platform/micro-frontends-challenges-app/issues/52

**Comment by sandhiyakavi** [comment]
Verified in Dev Env.

![image](https://user-images.githubusercontent.com/55895538/137260254-1c6a673f-121d-49d9-af5c-f08db1782d6d.png)
